### ISSUE TITLE
v 0.3.0.0

### ISSUE THREAD

**Issue by prawler74** [loki79uk/FS25_UniversalAutoload#172]
Hi

Just tested the newest release on our server (VeryGames). Still not updating the xml file on the server side.
Really frustrating. 
Keep up the good work loki

Best regards
Bjørn

**Comment by loki79uk** [comment]
Can you attach your log.  v.0.3.0.0 just does the same thing as before, but sooner, whereas your issue is something else that stops the file being written at all.

**Comment by prawler74** [comment]
Will do thst loki. Just went yo bed. Posting them both tomorrow. Off to work early. 

Bjørn

**Comment by loki79uk** [comment]
Suspect this is the same as https://github.com/loki79uk/FS25_UniversalAutoload/issues/173

Should be fixed now in https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by prawler74** [comment]
Hi. I see you have updated a couple of times since i tested last.
Just done a test now with the latest version. And my customizations does still not "stick" Will do a server restart to see..
Anyway, here is the log files, both client and server

[clientlog.txt](https://github.com/user-attachments/files/18219126/clientlog.txt)
[serverlog.txt](https://github.com/user-attachments/files/18219127/serverlog.txt)

Bjørn

**Comment by loki79uk** [comment]
what values were you expecting?

It looks like you bought the FS25_schwarzmuellerTimberTrailerSemi/timberTrailerSemi twice

first time was:
```
2024-12-21 16:46   >> .loadingArea(0)#width = 2.4642274129719057
2024-12-21 16:46   >> .loadingArea(0)#length = 12.442680828145587
2024-12-21 16:46   >> .loadingArea(0)#height = 2.5774327174369205
```

then second time:
```
2024-12-21 16:47   >> .loadingArea(0)#width = 2.6415109634399414
2024-12-21 16:47   >> .loadingArea(0)#length = 11.645072937011719
2024-12-21 16:47   >> .loadingArea(0)#height = 2.383267879486084
```

And the server got those both times, so the new vehicles should have had those sizes, with the second one now written to the sever mod settings file.

**Comment by prawler74** [comment]
Yes, i forgot i had to own it to customize, hence 2...my bad.
It seems like the server gets the information, but when i get in the shop to check, it is back to the standard setting....maybe it is supposed to be like this? 
How do i get those loadingboxes? is it in the Autoload section in the shop? 

Bjørn

**Comment by loki79uk** [comment]
Yes, currently that is how it is supposed to be.  In MP the server knows all the settings and we just send them.  It is a good question - what should happen when one player buys a new trailer - should all other players get their default updated with the new configuration?  Eventually, I think it will only be admins allowed to change anything.

What do you mean loading boxes?  If you mean the debugging display, then is only available in single player, or as a player host for MP.  Clients do not have any of the information needed since all calculations are done on the server.

**Comment by loki79uk** [comment]
Closing as this is the current expected behaviour.  Not sure how it should eventually work for different users on a MP server, since there is a conflict between having a single "global" setting for each vehicle type on the server, vs each player having their own different (also global to them) setting for each vehicle type.
