### ISSUE TITLE
Modded Trailers not loading on dedi server

### ISSUE THREAD

**Issue by Storz18** [loki79uk/FS25_UniversalAutoload#239]
[log.txt](https://github.com/user-attachments/files/18461661/log.txt)

Config for modded trailers does not seem to be saving and wont load trailers
config options are available in store
same trailers work perfectly on single player even on the same save I downloaded from the server
in game vanilla trailers work fine

**Comment by loki79uk** [comment]
It looks like the settings are being sent to the server.  Can you attach a server log please, and if possible also get the mod settings file from the server using FTP.

**Comment by Storz18** [comment]
thanks for the quick response
which file from the mod settings are you after it won't let me put an xml file in here

[log_2025-01-18_04-13-53.txt](https://github.com/user-attachments/files/18467346/log_2025-01-18_04-13-53.txt)

![Image](https://github.com/user-attachments/assets/0a882791-3d2f-46fc-97f8-9de4da61c694)

**Comment by Storz18** [comment]
[UniversalAutoload.txt](https://github.com/user-attachments/files/18467356/UniversalAutoload.txt) 
changed the xml to a txt file

**Comment by loki79uk** [comment]
Can you please try without `FS25_ToolDisplay`.  There are a lot of errors from it.

**Comment by Storz18** [comment]
[log_2025-01-19_21-59-28.txt](https://github.com/user-attachments/files/18472876/log_2025-01-19_21-59-28.txt)
this is the latest log Tool display has been removed and still the same issues

**Comment by loki79uk** [comment]
Have you tried a game with only UAL active?  There are quite a few other errors in your log file from earlier.

**Comment by FrmrJon** [comment]
I am having the same issue. I'm using Version 0.4.2.7 It is saying Warning, Load area missing. Check Settings file. I've checked the settings file and the configurations are there. I've tried with Just UAL and one Modded trailer on a base game map. I've attached the server log from when I tried on my main save, as well as the UAL mod settings file. 

Server log: [log_2025-01-26_06-05-28.txt](https://github.com/user-attachments/files/18549284/log_2025-01-26_06-05-28.txt)

Mod Settings: 

`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/krone/profiLiner/profiLiner.xml">
            <configuration selectedConfigs="ALL">
                <options isCurtainTrailer="true"/>
                <loadingArea offset="0 1.188 -0.123" width="2.44" height="2.50" length="13.4"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lizard/multiPurposeTruck/multiPurposeTruck.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.000 0.962 -0.960" width="1.854" length="3.585" height="1.85"/>
            </configuration>
            <configuration selectedConfigs="3">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 0.962 -0.960" width="1.890" length="3.585" height="1.85"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/international/cvSeries/cvSeries.xml">
            <configuration selectedConfigs="2|1" useConfigName="enterablePassenger">
                <options enableRearLoading="true" enableSideLoading="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 1.466 -1.728" width="2.342000" length="3.836105" height="2.356430"/>
            </configuration>
            <configuration selectedConfigs="2|2" useConfigName="enterablePassenger">
                <loadingArea offset="0.000 1.037 -2.544" width="2.225" length="3.836" height="2.340"/>
            </configuration>
            <configuration selectedConfigs="1|1" useConfigName="enterablePassenger">
                <loadingArea offset="-0.000 1.071 -2.190" width="1.983" length="4.345" height="1.869"/>
            </configuration>
            <configuration selectedConfigs="1|2" useConfigName="enterablePassenger">
                <loadingArea offset="-0.000 1.065 -3.006" width="1.983" length="4.345" height="1.876"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lizard/pickup2017/pickup2017.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" zonesOverlap="true" rearUnloadingOnly="true"/>
                <loadingArea offset="0.000 0.771 -1.352" width="1.140" length="2.275" height="1.500"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/international/series200/series200.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.000 0.923 -1.300" width="1.122" length="2.413" height="1.55"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/salek/ans1900/ans1900.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.000 0.59 -0.484" width="1.39" length="2.45" height="1.85"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/brantner/dd24073/dd24073.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.000 1.423 -0.765" width="2.410" height="2.650" length="7.3050" baleHeight="3.200"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 1.144 -0.820" width="2.400" length="9.728" height="2.403"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kroeger/pwo24/pwo24.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.001 1.276 -0.176" width="2.347" length="9.775" height="2.99"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/fliegl/dts59/dts59.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 1.211 -1.940" width="2.382" length="5.995" height="2.397"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="false" enableRearLoading="true" enableSideLoading="true"/>
                <loadingArea offset="-0.001 1.011 -0.330" width="2.45" height="2.25" length="11.2" baleHeight="2.8"/>
                <loadingArea offset="-0.001 1.444 7.020" width="2.45" height="2.25" length="3.20" baleHeight="2.8"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="false" enableRearLoading="true" enableSideLoading="true"/>
                <loadingArea offset="0 1.010 -1.00" width="2.45" height="2.25" length="11.1" baleHeight="2.8"/>
                <loadingArea offset="0 1.620 6.235" width="2.45" height="2.25" length="3.20" baleHeight="2.8"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/schwarzmueller/lowloader4A/lowloader4A.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.002 0.979 -1.213" width="2.405" length="8.455" height="2.405"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/brandt/h550/h550.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="-0.002 0.740 3.756" width="2.975" length="6.820" height="3.025"/>
                <loadingArea offset="0.000 1.083 -2.194" width="3.045" length="4.365" height="3.025"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/pittsTrailers/lt408L/lt408L.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.020 1.702 -0.096" width="2.290" length="12.600" height="2.25"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/riedler/timberFrameFH16/timberFrameFH16.xml">
            <configuration selectedConfigs="1">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.013 1.602 -1.109" width="2.060" length="5.855" height="2.65"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/riedler/timberTrailer3A/timberTrailer3A.xml">
            <configuration useConfigName="design" selectedConfigs="ALL|1">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -1.184" width="2.065" length="6.050" height="2.850"/>
            </configuration>
            <configuration useConfigName="design" selectedConfigs="ALL|2">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -1.182" width="2.065" length="6.280" height="2.850"/>
            </configuration>
            <configuration useConfigName="design" selectedConfigs="ALL|3">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -1.466" width="2.065" length="6.800" height="2.850"/>
            </configuration>
            <configuration useConfigName="design" selectedConfigs="ALL|4">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -1.837" width="2.065" length="7.650" height="2.850"/>
            </configuration>
            <configuration useConfigName="design" selectedConfigs="ALL|5">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -2.036" width="2.065" length="8.050" height="2.850"/>
            </configuration>
            <configuration useConfigName="design" selectedConfigs="ALL|6">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.280 -2.257" width="2.065" length="8.550" height="2.850"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kesla/nd144/nd144.xml">
            <configuration selectedConfigs="1">
                <options isLogTrailer="true"/>
                <loadingArea offset="-0.003 1.406 -0.173" width="2.254" length="3.995" height="1.625" lengthAxis="AXIS_FRONTLOADER_ARM2"/>
            </configuration>
            <configuration selectedConfigs="2">
                <options isLogTrailer="true"/>
                <loadingArea offset="-0.003 1.235 0.034" width="2.206" length="4.635" height="1.625" lengthAxis="AXIS_FRONTLOADER_ARM2"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_FLC253/profiLiner2.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.003 1.187 -0.119" width="2.455148" length="13.408045" height="2.562126"/>
            </configuration>
            <configuration selectedConfigs="2">
                <options enableRearLoading="true" enableSideLoading="true"/>
                <loadingArea offset="-0.004 1.187 0.179" width="2.367690" length="12.815646" height="2.562111"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_PhiberDash/vehicles/steelDropDeck/gooseneckhyd.xml">
            <configuration selectedConfigs="1">
                <options enableRearLoading="true" enableSideLoading="true"/>
                <loadingArea offset="-0.001 0.933 -1.405" width="2.457961" length="10.663336" height="2.334102"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_2019LimitedF250/19Limited.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.008 0.992 -2.626" width="1.595485" length="1.897948" height="1.542435"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_FreightlinerM2stakebed/freightlinerM2.xml">
            <configuration selectedConfigs="ALL">
                <options enableRearLoading="true" enableSideLoading="true"/>
                <loadingArea offset="-0.004 1.415 -1.197" width="2.608937" length="7.952635" height="2.402458"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="D:/FS25 Mods/KOE Server-Semi Vanilla/FS25_FreightlinerM2stakebed/freightlinerM2.xml">
            <configuration selectedConfigs="ALL">
                <options enableRearLoading="true" enableSideLoading="true" horizontalLoading="true" isBaleTrailer="true"/>
                <loadingArea offset="-0.004 1.382 -0.883" width="2.609058" length="7.350005" height="4.053380"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>
`

**Comment by loki79uk** [comment]
Do you have an example with both client and server logs from the same time?  I can see the settings were not sent to the server, but going but the other client log those settings were sent, so it doesn't make sense to me.  I'm away from my pc most of today, but I'll try to reproduce it later as well.

**Comment by loki79uk** [comment]
I think this is the same as #266 - should be fixed now in https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.2

**Comment by FrmrJon** [comment]
I've just tried version 0.4.3.2, and it's still not working. I take the truck to the repair trigger, and UAL is disabled. I re-enabled it, then clicked save vehicle settings, then changed the wheels, and clicked customize. I jump back into the truck and UAL is not enabled. I then did the same thing as above, saved the game, shut the server down, and then restarted the server, and the truck still did not have UAL enabled. I've attached another server log, and my client log.

Server Log: [log_2025-01-26_12-13-00.txt](https://github.com/user-attachments/files/18551891/log_2025-01-26_12-13-00.txt)

Client Log: [log.txt](https://github.com/user-attachments/files/18551892/log.txt)

**Comment by loki79uk** [comment]
Try changing the wheels or numberplate first before changing the autoload settings.  I'll see if I can change the order of events without breaking something else, but the problem at the moment is every time you change the workshop vehicle the game resets it to match the original one outside the shop.

**Comment by Storz18** [comment]
I've updated to 0.4.3.2 started a new server on a base game map only have UAL and the flatbed trailer mod I want to use as active mods on the server and it's worse now than before. I had some functionality on the older version, ie: I could change loading sides and even toggle full only items or not but it wouldn't load now it wont even save the settings to the trailer,  Config the trailer save everything customize it and don't even get the controls on the F1 help menu. go back into the shop and it says that UAL is not active again. I restarted the server and still the same

Before I started the new server save I deleted both the log and UAL xml on both server and client sides so they would be written fresh and not muddied with old data.

Server

[log_2025-01-26_23-09-26.txt](https://github.com/user-attachments/files/18552058/log_2025-01-26_23-09-26.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18552064/UniversalAutoload.txt)

Client

[log.txt](https://github.com/user-attachments/files/18552067/log.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18552069/UniversalAutoload.txt)

**Comment by loki79uk** [comment]
Thanks, that is really helpful to have fresh client and server files. I think I know what is going on, I'll look properly tomorrow after work.

**Comment by loki79uk** [comment]
I think I have figured it out - sorry it took so long.

The issue was that the new settings were sent to the server only, and not saved on the client.  On my PC, the server and client share the same settings folder/file so I could never reproduce this.

Anyway, hopefully this works as expected now:
https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.3

**Comment by Storz18** [comment]
So it appears to be saving settings now but still no action not even F1 menu commands and can't open global settings, I tried a second trailer to see if it was just the one I was using and still no go.
restarted server a couple of times
Same steps as before, clean logs settings both sides on another new save

Server launch
[log_2025-01-27_22-23-21.txt](https://github.com/user-attachments/files/18565665/log_2025-01-27_22-23-21.txt)


Restart 1
[log_2025-01-27_22-37-56.txt](https://github.com/user-attachments/files/18565673/log_2025-01-27_22-37-56.txt)

Restart 2
[log_2025-01-27_22-46-50.txt](https://github.com/user-attachments/files/18565679/log_2025-01-27_22-46-50.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18565688/UniversalAutoload.txt)

Client

[log.txt](https://github.com/user-attachments/files/18565694/log.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18565695/UniversalAutoload.txt)

**Comment by loki79uk** [comment]
Does this mod work with UAL in single player?  I'll have to look again tomorrow..

**Comment by loki79uk** [comment]
I just tested using this mod on my dedi server: https://www.farming-simulator.com/mod.php?mod_id=305275&title=fs2025

Steps:
- open shop
- select trailer
- open autoload settings
- toggle enable autoload setting on
- close autload settings (don't save)
- buy vehicle
- enter vehicle and start loading

[client_log.txt](https://github.com/user-attachments/files/18565955/client_log.txt)
[server_log.txt](https://github.com/user-attachments/files/18565956/server_log.txt)

All seems fine for me

The cause of your error to look for in the log is:
```
CREATE REAL VEHICLE: MaxiTrans Freighter T-Liner B Trailer
MaxiTrans Freighter T-Liner B Trailer: UAL SETTINGS NOT ADDED
SERVER - INITIALISE REAL UAL VEHICLE (ON LOAD) 399661
WARNING: load area missing - check settings file
onLoad: 293685
```

where as it should look like:
```
CREATE REAL VEHICLE: Ponge SPX 816
Ponge SPX 816: UAL ACTIVATED
SERVER - INITIALISE REAL UAL VEHICLE (ON LOAD) 368937
SERVER - INITIALISE UAL VEHICLE (ON LOAD 2) 368937
onLoad: 210986
```

**Comment by Storz18** [comment]
I can't work this out then, I just tried the same trailer as you and still get the same issues again with fresh logs and settings. 
could it be a server setting issue?

server

[log_2025-01-28_01-27-59.txt](https://github.com/user-attachments/files/18566809/log_2025-01-28_01-27-59.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18566813/UniversalAutoload.txt)

Client

[log.txt](https://github.com/user-attachments/files/18566816/log.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18566819/UniversalAutoload.txt)

**Comment by loki79uk** [comment]
I'll try making a version with all the debugging outputs I can think of to see if we can sport some differences..

**Comment by loki79uk** [comment]
I added some extra debugging in the latest release.  Won't change the behaviour, but will maybe help to figure out what is wrong!

https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.4

**Comment by loki79uk** [comment]
Please try this one now (still not fixed, but was potential error printing a nil table before):
https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.5

**Comment by Storz18** [comment]
Still the same and unable to show debugging on 0.4.3.5

server

[log_2025-01-29_05-50-39.txt](https://github.com/user-attachments/files/18583426/log_2025-01-29_05-50-39.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18583427/UniversalAutoload.txt)

client

[log.txt](https://github.com/user-attachments/files/18583430/log.txt)

[UniversalAutoload.txt](https://github.com/user-attachments/files/18583436/UniversalAutoload.txt)

**Comment by loki79uk** [comment]
I am optimistic that this might be fixed now..
https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.6

**Comment by Raverontour** [comment]
unfortunately still the same problem


https://workupload.com/start/2jEfqW7f75X

**Comment by Raverontour** [comment]
unfortunately still the same problem

https://workupload.com/start/2jEfqW7f75X

**Comment by loki79uk** [comment]
I think I've found the cause!

```lua
		local fullPath = "Z:/data/si-4396/swi-8427/mods/ACM_MaxiTrans_Freighter_Semi/BTrailer.xml"
		local modsDirectory = "Z:/data/si-4396/swi-8427/mods/"
		print("gsub: " .. fullPath:gsub(modsDirectory, ""))
```

produces the output:
```
2025-01-30 18:20 gsub: Z:/data/si-4396/swi-8427/mods/ACM_MaxiTrans_Freighter_Semi/BTrailer.xml
```

It was hiding in plain sight all the time..

**Comment by loki79uk** [comment]
It must be that one of the server hosting companies uses that format with dashes in the path, and that causes the issue.

```lua
-- UNEXPECTED RESULT:
local fullPath = "Z:/data/si-4396/swi-8427/mods/ACM_MaxiTrans_Freighter_Semi/BTrailer.xml"
local modsDirectory = "Z:/data/si-4396/swi-8427/mods/"
print("gsub: " .. fullPath:gsub(modsDirectory, ""))

-- EXPECTED RESULT:
local fullPath2 = "Z:/data/si4396/swi8427/mods/ACM_MaxiTrans_Freighter_Semi/BTrailer.xml"
local modsDirectory2 = "Z:/data/si4396/swi8427/mods/"
print("gsub2: " .. fullPath2:gsub(modsDirectory2, ""))
```

proposed fix:
```lua
if fullPath:find(modsDirectory, 1, true) then
	cleanPath = fullPath:sub(#modsDirectory + 1)
	print(" sub: " .. cleanPath)
end
```

**Comment by loki79uk** [comment]
Which mod won't unload?  Does it happen in SP too?  Usually, when that happens it is because some trigger or non visible component of the mod has the wrong collision flags set.

**Comment by Raverontour** [comment]
https://www.farming-simulator.com/mod.php?mod_id=307144&title=fs2025

In the SP it worked perfectly

**Comment by loki79uk** [comment]
> https://www.farming-simulator.com/mod.php?mod_id=307144&title=fs2025
> 
> In the SP it worked perfectly
> 
> https://workupload.com/start/NYxA8dquqat

It is working for me in MP:

![Image](https://github.com/user-attachments/assets/2105eee9-ea32-4577-84f8-c3af68d2e941)

![Image](https://github.com/user-attachments/assets/c85ca3f5-cfb4-4b2d-a3f6-9059b2bfaf03)

**Comment by Raverontour** [comment]
Strangely, the one with page sharing works and the one without doesn't 
all the same settings 
I restart the server again

**Comment by Raverontour** [comment]
After I restarted the server (for the 5th time) it now works 

Thank you very much for the mod, which now runs as it should on the server

**Comment by Storz18** [comment]
We have a winner!
Thankyou so much Loki for all your hard work and persistence, a lot of other modders would have just said "well it works on my end so it must be your problem" but you kept looking, didn't dismiss the issue and eventually found a solution and for that myself and I'm sure the rest of the community appreciate that commitment.
Thanks again mate your a champion.

**Comment by loki79uk** [comment]
You are most welcome!  It is annoying it was such a dumb mistake, but at least I have found it now.

It would never have happened if the hosting companies stuck to alphanumeric windows paths like normal people, lol
