### ISSUE TITLE
Autoload can't load anything anymore

### ISSUE THREAD

**Issue by Lucas-Brand** [loki79uk/FS25_UniversalAutoload#266]
Hello Loki,

Yes, but you can't charge anything since version v0.4.2.6 because there is no interaction in the F1 menu. See screenshot.

I'm currently using version v0.4.3.1

As soon as you turn on the autoload in the shop, you can save everything. And when you have left the shop again, the car lot is deactivated again.

I'll send you a server log and my gamelog

![Image](https://github.com/user-attachments/assets/c672b867-c1e4-44a3-a201-997d3983505a)

Gamelog

[log.txt](https://github.com/user-attachments/files/18549688/log.txt)

Severlog

[log_2025-01-26_11-04-06.txt](https://github.com/user-attachments/files/18549689/log_2025-01-26_11-04-06.txt)

**Comment by loki79uk** [comment]
Thanks - I see what is happening now - the new disabled flag is not being sent back from the server.  I'll add it to the next fix shortly

**Comment by loki79uk** [comment]
Should be fixed now in https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.2

**Comment by Haurshi** [comment]
is not fixed, the kronetrai8ler only loads 2 rows and if you switch to standard in the autoload config at the dealer nothing works anymore

**Comment by loki79uk** [comment]
I can't reproduce that - are you changing the numberplate or some other option when you configure in the shop?

**Comment by Haurshi** [comment]
Sorry, it's confusing right now, I went to the server and autoload on the Krone didn't work at all, no keyboard display. So I went to the dealer to configure it and switched on autoload because it was off for whatever reason but it doesn't matter, it's just a new version. I could only load 2 pallets next to each other, I configured again, set certain to standard and it didn't work again. Now I've reset it again and suddenly it's loading 3 next to each other like always. Strange

**Comment by loki79uk** [comment]
When you say reset - you mean you are clicking "reset to shop"?

It shouldn't be switching off autoload though.  I think it must be that your local machine doesn't have any configuration saved.  The one you send to the server should get applied to every new instance of that vehicle though.

**Comment by loki79uk** [comment]
> Sorry, it's confusing right now, I went to the server and autoload on the Krone didn't work at all, no keyboard display. So I went to the dealer to configure it and switched on autoload because it was off for whatever reason but it doesn't matter, it's just a new version. I could only load 2 pallets next to each other, I configured again, set certain to standard and it didn't work again. Now I've reset it again and suddenly it's loading 3 next to each other like always. Strange

So when you say "I configured again, set certain to standard and it didn't work again" - did you actually apply some change to the vehicle (change numberplate and apply), or did you just click the button to save settings and then exit the shop?  If you didn't apply some changes then it makes sense that nothing would happen until you reset the vehicle or restarted the server.

**Comment by Haurshi** [comment]
yes reset to shop and yes autoload set and then configure press that is logical :-P

**Comment by Lucas-Brand** [comment]
With me I can't charge more than three mission tribes.

and I've already reconfigured it.

![Image](https://github.com/user-attachments/assets/13244154-4862-4a58-8d31-dd4f23e15306)

as soon as I leave the shop, the autoload is deactivated again. 
See Gamelog

[log.txt](https://github.com/user-attachments/files/18550773/log.txt)

**Comment by loki79uk** [comment]
> yes reset to shop and yes autoload set and then configure press that is logical :-P

So I don't see the problem?  When you click the button to save the settings to the server it will apply to all new vehicles created after that point, but it will not update any existing vehicles until you restart the server.

**Comment by Haurshi** [comment]
Apparently it just didn't work the first time, now everything is back to normal strangely enough

**Comment by loki79uk** [comment]
I think it was only an issue if the settings did not exist on the client.  So if you already had something configured from SP, etc then it would work.  Should be fixed now: https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.4.3.3

**Comment by Haurshi** [comment]
ok and very thanks for the Mod btw

**Comment by Lucas-Brand** [comment]
I can only agree with that, thank you for the great mod
